<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>IdleDesktop</RootNamespace>
        <ApplicationIcon>app.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="app.ico" LogicalName="app.ico" />
        <InternalsVisibleTo Include="IdleDesktop.Tests" />
    </ItemGroup>

</Project>